name: GraalVM Native Image build
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    name: Build native-image on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: graalvm/setup-graalvm@v1
        with:
          version: '21.2.0'
          java-version: '11'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Enable testcontainer reuse
        run: echo 'testcontainers.reuse.enable=true' > "$HOME/.testcontainers.properties"
      - name: Run tests and build with Maven
        run: mvn --batch-mode --update-snapshots clean verify --file pom.xml -DtrimStackTrace=false
        env:
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: executable-${{ matrix.os }}
          path: target/${{ github.event.repository.name }}