name: Release Droid - Prepare Original Checksum
on:
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: true
      - name: Set up JDK
        # We need a JDK additionally to GraalVM to configure Maven toolchain
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "21"
          # Disable caching to avoid cache poisoning of release build
      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@bef4b0e916c7dd079bf60fb95d49139f67e32c5f # v1.5.3
        # This will define GRAALVM_HOME used by native-maven-plugin
        with:
          java-version: "25"
          distribution: "graalvm-community"
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run tests and build with Maven
        run: mvn --batch-mode clean verify -DossindexSkip=true
      - name: Prepare checksum
        run: find target -maxdepth 1 -name *.jar -exec sha256sum "{}" + > original_checksum
      - name: Upload checksum to the artifactory
        uses: actions/upload-artifact@v7
        with:
          name: original_checksum
          retention-days: 5
          path: original_checksum
