name: Release Droid - Print Quick Checksum
on:
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Set up JDK
        # We need a JDK additionally to GraalVM to configure Maven toolchain
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "17"
          # Disable caching to avoid cache poisoning of release build
      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@bef4b0e916c7dd079bf60fb95d49139f67e32c5f # v1.5.3
        # This will define GRAALVM_HOME used by native-maven-plugin
        with:
          java-version: "17"
          distribution: "graalvm-community"
          components: "native-image"
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build with Maven skipping tests
        run: mvn --batch-mode clean verify -DskipTests -DossindexSkip=true
      - name: Print checksum
        run: echo 'checksum_start==';find target -maxdepth 1 -name *.jar -exec sha256sum "{}" + | xargs;echo '==checksum_end'
