name: Release Droid - Upload GitHub Release Assets

on:
  workflow_dispatch:
    inputs:
      upload_url:
        description: "Assets upload URL"
        required: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        include:
          - os: windows-latest
            binary: parquet-edml-generator-win_x86
            suffix: .exe
          - os: ubuntu-latest
            binary: parquet-edml-generator-linux_x86
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: graalvm/setup-graalvm@v1
        with:
          version: "22.3.1"
          java-version: "11"
          components: "native-image"
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven skipping tests
        run: mvn --batch-mode clean verify -DskipTests
      - name: Rename binary to ${{ matrix.binary }}${{ matrix.suffix }}
        run: mv "target/parquet-edml-generator${{ matrix.suffix }}" "target/${{ matrix.binary }}${{ matrix.suffix }}"

      - name: Generate sha256sum files for JARs
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: cd target && find . -maxdepth 1 -name *.jar -exec bash -c 'sha256sum {} > {}.sha256' \;

      - name: Generate sha256sum for binary (Unix)
        if: ${{ matrix.os != 'windows-latest' }}
        run: cd target && shasum --algorithm 256 "${{ matrix.binary }}${{ matrix.suffix }}" > ${{ matrix.binary }}${{ matrix.suffix }}.sha256

      - name: Generate sha256sum for binary (Windows)
        shell: pwsh
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          cd target
          $PSDefaultParameterValues['Out-File:Encoding'] = 'utf8'
          (Get-FileHash ${{ matrix.binary }}${{ matrix.suffix }} -Algorithm SHA256).Hash.ToLower() > ${{ matrix.binary }}${{ matrix.suffix }}.sha256

      - name: Upload binary to the GitHub release draft
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.inputs.upload_url }}
          asset_path: target/${{ matrix.binary }}${{ matrix.suffix }}

      - name: Upload sha256sum for binary to the GitHub release draft
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.inputs.upload_url }}
          asset_path: target/${{ matrix.binary }}${{ matrix.suffix }}.sha256

      - name: Upload jar and sha256 checksum file
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.inputs.upload_url }}
          asset_path: target/*.jar*

      - name: Upload error-code-report
        uses: shogo82148/actions-upload-release-asset@v1
        if: ${{ matrix.os == 'ubuntu-latest' }}
        with:
          upload_url: ${{ github.event.inputs.upload_url }}
          asset_path: target/error_code_report.json
