name: Release Droid - Prepare Original Checksum
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        # This will define GRAALVM_HOME used by native-maven-plugin
        with:
          java-version: "17"
          distribution: "graalvm-community"
          components: "native-image"
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up JDK
        # We need a JDK additionally to GraalVM to configure Maven toolchain
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven
      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Run tests and build with Maven
        run: mvn --batch-mode clean verify --file pom.xml
      - name: Prepare checksum
        run: find target -maxdepth 1 -name *.jar -exec sha256sum "{}" + > original_checksum
      - name: Upload checksum to the artifactory
        uses: actions/upload-artifact@v4
        with:
          name: original_checksum
          retention-days: 5
          path: original_checksum
